# Generated by Django 5.0.9 on 2026-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('brand', models.CharField(blank=True, default='', max_length=64, verbose_name='品牌')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('low_stock_threshold', models.IntegerField(default=1, help_text='单个货道库存低于此值时报警', verbose_name='低库存预警阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'gush_product',
                'ordering': ['-created_at'],
            },
        ),
    ]
