# Generated by Django 5.0.9 on 2026-05-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=0, help_text='仓库剩余可补货数量。补货到货道时扣减；入库时增加。', verbose_name='仓库总库存'),
        ),
    ]
