# Generated by Django 5.0.9 on 2026-05-20 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('products', '0002_product_total_stock'),
        ('projects', '0002_project_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inbound', '入库'), ('restock_out', '补货出库（仓库扣减）'), ('restock_in', '补货上机（货道增加）'), ('dispense', '派样出货'), ('return_out', '回库下机（货道扣减）'), ('return_in', '回库归仓（仓库增加）'), ('adjust', '人工调整')], db_index=True, max_length=16, verbose_name='事件类型')),
                ('quantity', models.IntegerField(verbose_name='数量（绝对值）')),
                ('channel_code', models.CharField(blank=True, default='', max_length=4, verbose_name='货道编码快照')),
                ('warehouse_after', models.IntegerField(blank=True, null=True, verbose_name='操作后仓库库存')),
                ('channel_stock_after', models.IntegerField(blank=True, null=True, verbose_name='操作后货道库存')),
                ('source', models.CharField(blank=True, default='', help_text='manual / restock / dispense / motor_done / redeem / return / system', max_length=32, verbose_name='来源')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='devices.channel', verbose_name='涉及货道')),
                ('dispense_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='devices.dispenselog', verbose_name='关联出货日志')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='devices.machine', verbose_name='涉及设备')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('paired_with', models.ForeignKey(blank=True, help_text='补货/回库时另一半的流水 id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='products.stockmovement', verbose_name='配对记录')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='礼品')),
                ('redeem_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='projects.redeemcode', verbose_name='关联兑换码')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'gush_stock_movement',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='gush_stock__product_500150_idx'), models.Index(fields=['machine', '-created_at'], name='gush_stock__machine_572307_idx'), models.Index(fields=['kind', '-created_at'], name='gush_stock__kind_9e9ecc_idx')],
            },
        ),
    ]
