# Generated by Django 5.0.9 on 2026-05-18 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='结束时间')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='活动海报')),
                ('wechat_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='企业微信二维码')),
                ('rules_text', models.TextField(blank=True, default='', verbose_name='活动规则')),
                ('code_length', models.IntegerField(default=8, verbose_name='兑换码长度')),
                ('code_validity_days', models.IntegerField(default=7, verbose_name='兑换码有效天数')),
                ('max_per_user', models.IntegerField(default=1, verbose_name='每用户最多兑换次数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '进行中'), ('paused', '已暂停'), ('finished', '已结束')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '活动项目',
                'verbose_name_plural': '活动项目',
                'db_table': 'gush_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'gush_project_machine',
                'unique_together': {('project', 'machine')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='machines',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMachine', to='devices.machine', verbose_name='关联设备'),
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='兑换码')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期'), ('revoked', '已作废')], default='unused', max_length=16, verbose_name='状态')),
                ('user_openid', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='用户OpenID')),
                ('user_nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='用户昵称')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('used_on_channel_code', models.CharField(blank=True, default='', max_length=4, verbose_name='使用货道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_codes', to='projects.project')),
                ('used_on_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to='devices.machine')),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
                'db_table': 'gush_redeem_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='gush_redeem_project_eb2768_idx')],
            },
        ),
    ]
