# Generated by Django 5.0.9 on 2026-05-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_total_stock'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='勾选后，给本项目设备补货时只能选这些礼品。', related_name='projects', to='products.product', verbose_name='本活动派发的礼品'),
        ),
    ]
