# Generated by Django 5.0.9 on 2026-05-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagevisitlog'),
        ('projects', '0002_project_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='claim_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_codes', to='pages.pagevisitlog', verbose_name='领取来源访问'),
        ),
    ]
