# Generated by Django 5.0.9 on 2026-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_claim_daily_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daily_per_user_per_machine',
            field=models.BooleanField(default=True, help_text='开启后，同一用户在同一台设备上 24 小时内只能成功兑换一次。勾选适合大多数场景；关掉则仅依赖 max_per_user 总次数限制。', verbose_name='每用户每设备每天限领一次'),
        ),
        migrations.AddField(
            model_name='project',
            name='daily_window_start_hour',
            field=models.IntegerField(default=6, help_text='0 表示每天 00:00-次日 00:00；6 表示每天 06:00-次日 06:00；当天 6 点后首次使用算作当天，6 点前的算前一天。', verbose_name='自然日起始小时(0-23)'),
        ),
    ]
