# Generated by Django 5.0.9 on 2026-05-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warn', '警告'), ('critical', '严重')], default='warn', max_length=16, verbose_name='级别')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='故障代码')),
                ('message', models.CharField(max_length=255, verbose_name='故障描述')),
                ('resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障记录',
                'verbose_name_plural': '故障记录',
                'db_table': 'gush_fault_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='接收时间')),
                ('signal_strength', models.IntegerField(default=0, verbose_name='信号强度')),
                ('network_type', models.CharField(blank=True, default='', max_length=16, verbose_name='网络类型')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='原始上报数据')),
            ],
            options={
                'verbose_name': '心跳记录',
                'verbose_name_plural': '心跳记录',
                'db_table': 'gush_heartbeat_log',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, help_text='格式：MACHINE001（系统自动生成）', max_length=32, unique=True, verbose_name='设备编号')),
                ('subdomain', models.CharField(help_text='自动生成，例如 machine001，最终访问 machine001.koarkailash.com', max_length=64, unique=True, verbose_name='子域名前缀')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='安装地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('activation_code', models.CharField(help_text='设备首次接入时使用，激活后失效', max_length=64, verbose_name='激活码')),
                ('comm_secret', models.CharField(help_text='HMAC 签名密钥，用于设备↔服务器之间的消息验签', max_length=128, verbose_name='通信密钥')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障')], default='offline', max_length=16, verbose_name='状态')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('signal_strength', models.IntegerField(default=0, verbose_name='信号强度(%)')),
                ('network_type', models.CharField(blank=True, default='', max_length=16, verbose_name='网络类型')),
                ('runtime_seconds', models.BigIntegerField(default=0, verbose_name='累计运行秒数')),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32, verbose_name='固件版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '派样机',
                'verbose_name_plural': '派样机',
                'db_table': 'gush_machine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1, verbose_name='行(A-F)')),
                ('col', models.IntegerField(verbose_name='列(0-9)')),
                ('channel_code', models.CharField(help_text='A0–F9，与 STM32 协议一致', max_length=4, verbose_name='货道编码')),
                ('layer', models.IntegerField(help_text='UI 展示用：A行=1层 ... F行=6层', verbose_name='层号(1-6)')),
                ('capacity', models.IntegerField(default=5, verbose_name='容量')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('status', models.CharField(choices=[('normal', '正常'), ('low', '库存低'), ('empty', '缺货'), ('fault', '故障')], default='empty', max_length=16, verbose_name='状态')),
                ('last_dispense_at', models.DateTimeField(blank=True, null=True, verbose_name='最后出货时间')),
                ('fault_message', models.CharField(blank=True, default='', max_length=255, verbose_name='故障信息')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='products.product', verbose_name='绑定商品')),
            ],
            options={
                'verbose_name': '货道',
                'verbose_name_plural': '货道',
                'db_table': 'gush_channel',
                'ordering': ['machine', 'row', 'col'],
            },
        ),
        migrations.CreateModel(
            name='DispenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_code', models.CharField(max_length=4, verbose_name='货道编码快照')),
                ('result', models.CharField(choices=[('success', '成功'), ('empty', '货道空/机械故障'), ('busy', '设备忙'), ('timeout', '超时'), ('error', '未知错误')], max_length=16, verbose_name='结果')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='devices.channel')),
            ],
            options={
                'verbose_name': '出货记录',
                'verbose_name_plural': '出货记录',
                'db_table': 'gush_dispense_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
