# Generated by Django 5.0.9 on 2026-05-22 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('pages', '0002_ledpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_override', models.JSONField(blank=True, default=dict, verbose_name='主题覆盖')),
                ('h5_override', models.JSONField(blank=True, default=dict, verbose_name='H5 覆盖')),
                ('led_override', models.JSONField(blank=True, default=dict, verbose_name='LED 覆盖')),
                ('led_qr_image', models.ImageField(blank=True, null=True, upload_to='pages/overrides/led_qr/', verbose_name='LED 二维码（覆盖）')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用覆盖')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_override', to='devices.machine', verbose_name='目标设备')),
            ],
            options={
                'verbose_name': '设备页面覆盖',
                'verbose_name_plural': '设备页面覆盖',
                'db_table': 'gush_device_page_override',
            },
        ),
    ]
