# Generated by Django 5.0.9 on 2026-05-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('pages', '0004_pagevisitlog'),
        ('projects', '0003_redeemcode_claim_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4, verbose_name='变体 key')),
                ('name', models.CharField(default='', max_length=64, verbose_name='变体名称')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('h5_snapshot', models.JSONField(default=dict, verbose_name='H5 内容快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '实验变体',
                'verbose_name_plural': '实验变体',
                'db_table': 'gush_experiment_variant',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='pagevisitlog',
            name='variant_key',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='命中变体'),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A/B 实验', max_length=128, verbose_name='实验名称')),
                ('hypothesis', models.TextField(blank=True, default='', help_text='例：使用红色按钮可提升点击率', verbose_name='假设')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '进行中'), ('stopped', '已暂停'), ('concluded', '已结束')], default='draft', max_length=16, verbose_name='状态')),
                ('traffic_split_b', models.IntegerField(default=50, help_text='0-100，剩余流量进 A', verbose_name='B 变体流量占比(%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('winner', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], default='', max_length=4, verbose_name='胜出变体')),
                ('conclusion_note', models.CharField(blank=True, default='', max_length=255, verbose_name='结论备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'A/B 实验',
                'verbose_name_plural': 'A/B 实验',
                'db_table': 'gush_experiment',
            },
        ),
        migrations.AddField(
            model_name='pagevisitlog',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='pages.experiment'),
        ),
        migrations.AddIndex(
            model_name='pagevisitlog',
            index=models.Index(fields=['experiment', 'variant_key', '-visited_at'], name='gush_page_v_experim_0dbf14_idx'),
        ),
        migrations.AddField(
            model_name='experimentvariant',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pages.experiment'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentvariant',
            unique_together={('experiment', 'key')},
        ),
    ]
