# Generated by Django 5.0.9 on 2026-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_experimentvariant_pagevisitlog_variant_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentvariant',
            name='traffic_share',
            field=models.IntegerField(default=50, help_text='单个变体的流量分配 0-100；所有变体之和 = 100', verbose_name='流量占比 %'),
        ),
    ]
