

#LOG_FILE="/home/ubuntu/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='admin@koarkailash.com'
UPGRADE_HASH='f265c304daf53afdf26c3e6346f393d9d098c804'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
SAVED_Tencent_SecretId='AKIDlQyKSO6bsxqY4MQHvfDYgaJrCKGzUr1y'
SAVED_Tencent_SecretKey='oPgldKo46vXw86sTr1yoSt9C1d2GLF7n'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games'
