# Generated by Django 5.0.9 on 2026-05-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('pages', '0005_experimentvariant_pagevisitlog_variant_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, verbose_name='观测时间')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16, verbose_name='性别')),
                ('gender_confidence', models.FloatField(default=0.0, verbose_name='性别置信度')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='估算年龄')),
                ('age_range', models.CharField(choices=[('child', '儿童 (0-12)'), ('teen', '青少年 (13-17)'), ('young_adult', '青年 (18-30)'), ('adult', '中年 (31-50)'), ('senior', '中老年 (51+)'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16, verbose_name='年龄段')),
                ('dominant_emotion', models.CharField(choices=[('happy', '开心'), ('neutral', '平静'), ('surprised', '惊讶'), ('sad', '悲伤'), ('angry', '生气'), ('disgusted', '厌恶'), ('fear', '害怕'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16, verbose_name='主导情绪')),
                ('emotion_scores', models.JSONField(blank=True, default=dict, help_text='7 种情绪各自打分 0-100', verbose_name='情绪打分明细')),
                ('is_smiling', models.BooleanField(default=False, verbose_name='是否微笑')),
                ('source', models.CharField(default='image_upload', help_text='image_upload=服务器推理 | qt_inference=Qt 端推理直传', max_length=16, verbose_name='来源')),
                ('inference_meta', models.JSONField(blank=True, default=dict, help_text='包含 model_version, latency_ms, face_bbox 等', verbose_name='推理元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_observations', to='devices.machine', verbose_name='来源设备')),
                ('matched_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_observation', to='pages.pagevisitlog', verbose_name='关联访问')),
            ],
            options={
                'verbose_name': '人脸画像观测',
                'verbose_name_plural': '人脸画像观测',
                'db_table': 'gush_face_observation',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['machine', '-observed_at'], name='gush_face_o_machine_59b05e_idx'), models.Index(fields=['gender', 'age_range'], name='gush_face_o_gender_2850cb_idx')],
            },
        ),
    ]
