CA_EMAIL='admin@koarkailash.com'
CA_EAB_KEY_ID='ET5ZHUAXBiS71KWi5MGVzA'
CA_EAB_HMAC_KEY='WiAu-qLRIVmdxSq8ILC4Pp7bMDVCvbyvo0tXWUtmKUITHJ2U5aYjyPmbGahNDKs7kuROo2_U2F8v5kAGFl1P0A'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/ET5ZHUAXBiS71KWi5MGVzA'
CA_KEY_HASH='SGkFngo4UOMS2WHL+JFVguFYACBiXxjof0W1YMjXxxU='
