# Generated by Django 5.0.9 on 2026-05-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenselog',
            name='redeem_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_logs', to='projects.redeemcode'),
        ),
        migrations.AddField(
            model_name='faultlog',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.channel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='bound_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_machines', to='projects.project', verbose_name='当前绑定项目'),
        ),
        migrations.AddField(
            model_name='heartbeatlog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.machine'),
        ),
        migrations.AddField(
            model_name='faultlog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='devices.machine'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='devices.machine'),
        ),
        migrations.AddField(
            model_name='channel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.machine', verbose_name='所属设备'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['machine', 'status'], name='gush_channe_machine_5de1e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('machine', 'channel_code')},
        ),
    ]
