# Generated by Django 5.0.9 on 2026-05-19 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名快照')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=8, verbose_name='HTTP方法')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='响应码')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='UA')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='operations__created_ba2780_idx'), models.Index(fields=['user'], name='operations__user_id_7429e8_idx')],
            },
        ),
    ]
