# Generated by Django 5.0.9 on 2026-05-21 02:26

import apps.pages.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='H5Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='填写信息', max_length=64, verbose_name='页面标题')),
                ('header_subtitle', models.CharField(default='获取您的专属兑换码', max_length=128, verbose_name='副标题')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='内容区块')),
                ('form_fields', models.JSONField(default=apps.pages.models._default_form_fields, verbose_name='表单字段')),
                ('privacy', models.JSONField(default=apps.pages.models._default_privacy, verbose_name='隐私协议配置')),
                ('submit_button', models.JSONField(default=apps.pages.models._default_submit_button, verbose_name='提交按钮')),
                ('rate_limit', models.CharField(choices=[('none', '无限制'), ('per_device_day', '每设备每天 1 次'), ('per_phone_day', '每手机号每天 1 次'), ('per_openid_day', '每微信用户每天 1 次')], default='per_device_day', max_length=32, verbose_name='限频策略')),
                ('success_view', models.JSONField(default=apps.pages.models._default_success_view, verbose_name='成功视图配置')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发布时间')),
                ('current_version', models.IntegerField(default=0, verbose_name='当前已发布版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='h5_page', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'H5 落地页',
                'verbose_name_plural': 'H5 落地页',
                'db_table': 'gush_h5_page',
            },
        ),
        migrations.CreateModel(
            name='PageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_color', models.CharField(default='#14B450', max_length=16, verbose_name='品牌主色')),
                ('accent_color', models.CharField(default='#0a0a0a', max_length=16, verbose_name='辅助色')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=16, verbose_name='文字主色')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pages/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='pages/favicons/', verbose_name='Favicon')),
                ('background_type', models.CharField(choices=[('color', '纯色'), ('image', '图片'), ('gradient', '渐变')], default='color', max_length=16, verbose_name='背景类型')),
                ('background_value', models.TextField(blank=True, default='#0a0a0a', verbose_name='背景值')),
                ('background_image', models.ImageField(blank=True, help_text='background_type=image 时生效', null=True, upload_to='pages/bg/', verbose_name='背景图')),
                ('font_family', models.CharField(default='"Noto Sans SC", -apple-system, sans-serif', max_length=128, verbose_name='字体')),
                ('shared_assets', models.JSONField(blank=True, default=list, verbose_name='共享资源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_theme', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '页面主题',
                'verbose_name_plural': '页面主题',
                'db_table': 'gush_page_theme',
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('theme', '主题'), ('h5', 'H5 落地页'), ('led', 'LED 大屏页')], db_index=True, max_length=16, verbose_name='页面类型')),
                ('page_id', models.IntegerField(db_index=True, verbose_name='页面ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(default=dict, verbose_name='快照内容')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='发布说明')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to='projects.project', verbose_name='所属项目')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '页面版本',
                'verbose_name_plural': '页面版本',
                'db_table': 'gush_page_version',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['project', 'page_type', '-version'], name='gush_page_v_project_74c454_idx')],
                'unique_together': {('page_type', 'page_id', 'version')},
            },
        ),
    ]
