# Generated by Django 5.0.9 on 2026-05-21 07:19

import apps.pages.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('projects', '0002_project_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, default='', max_length=64, verbose_name='标题')),
                ('header_subtitle', models.CharField(blank=True, default='', max_length=128, verbose_name='副标题')),
                ('ads', models.JSONField(blank=True, default=apps.pages.models._default_led_ads, verbose_name='广告轮播资源')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='pages/led/qr/', verbose_name='企微二维码图')),
                ('qr', models.JSONField(default=apps.pages.models._default_led_qr, verbose_name='二维码文案配置')),
                ('input_config', models.JSONField(default=apps.pages.models._default_led_input, verbose_name='输入区配置')),
                ('footer_tip', models.CharField(blank=True, default='出货完成请到取货口领取', max_length=255, verbose_name='底部提示')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发布时间')),
                ('current_version', models.IntegerField(default=0, verbose_name='当前已发布版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='led_page', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'LED 大屏页',
                'verbose_name_plural': 'LED 大屏页',
                'db_table': 'gush_led_page',
            },
        ),
    ]
