# Generated by Django 5.0.9 on 2026-05-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        ('pages', '0003_devicepageoverride'),
        ('projects', '0002_project_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('h5', 'H5 落地页'), ('led', 'LED 大屏页')], db_index=True, max_length=16, verbose_name='页面类型')),
                ('device_fp', models.CharField(blank=True, db_index=True, default='', help_text='前端 localStorage 持久化的 UUID', max_length=64, verbose_name='设备指纹')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='UA')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='访客 IP')),
                ('referrer', models.CharField(blank=True, default='', max_length=512, verbose_name='来源')),
                ('utm_source', models.CharField(blank=True, default='', max_length=64, verbose_name='utm_source')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64, verbose_name='utm_campaign')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='devices.machine')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.project')),
            ],
            options={
                'verbose_name': '页面访问',
                'verbose_name_plural': '页面访问',
                'db_table': 'gush_page_visit',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['project', 'page_type', '-visited_at'], name='gush_page_v_project_3836cc_idx'), models.Index(fields=['machine', '-visited_at'], name='gush_page_v_machine_0eac29_idx')],
            },
        ),
    ]
