# Generated by Django 5.0.9 on 2026-05-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_experiment_winner'),
        ('projects', '0003_redeemcode_claim_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepageoverride',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text='此设备 LED / 子域名落地页绑定的项目。多项目共存时必须显式指定。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_devices', to='projects.project', verbose_name='活跃项目'),
        ),
    ]
