Le_Domain='koarkailash.com'
Le_Alt='*.koarkailash.com'
Le_Webroot='dns_tencent'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/3364295656/514100500396'
Le_DNSSleep='60'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/3364295656/514100500396'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/06559c79e6b852cd6d09e787467b741d86e4'
Le_CertCreateTime='1779581709'
Le_CertCreateTimeStr='2026-05-24T00:15:09Z'
Le_NextRenewTimeStr='2026-06-22T00:15:09Z'
Le_NextRenewTime='1782087309'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/tmp/privkey.pem'
Le_ReloadCmd='__ACME_BASE64__START_dHJ1ZQ==__ACME_BASE64__END_'
Le_RealFullChainPath='/tmp/fullchain.pem'
